### ISSUE TITLE
Please consider adding support for Linux Azure DevOps agents

### ISSUE THREAD

**Issue by MarkDerman** [shayki5/azure-devops-create-pr-task#148] opened 2022-09-07 10:30 UTC
Having just tried this extension in my pipeline, I see in the docs that only Windows agents are supported...

![image](https://user-images.githubusercontent.com/746305/188856599-1d8e8bd0-d526-430a-8da5-fc5b09201983.png)

Support for LInux agents would be wonderful, if possible.

Regards,
Mark

**Comment by shayki5** [comment] 2022-09-07 14:25
Hi, there is an open PR for that, i need time to implement it... #145 
I closing it because it's a duplicate of #22.

**Closed by shayki5** 2022-09-07 14:25 UTC
