### ISSUE TITLE
Feature request: Possibility to set pull request creator

### ISSUE THREAD

**Issue by wouterroos** [shayki5/azure-devops-create-pr-task#55] opened 2020-07-22 07:32 UTC
Hi,

First of all, great work on creating this task! It really helps us in achieving some of the more complicated flows in Azure DevOps. I was wondering if it is possible to change the 'creator' of the pull request to a specific user (e.g. by email address). Currently, the pull request is always created by the 'Project Collection Build Service' user/identity. This makes sense from a technical point of view since this is the user that is also running the pipeline that is invoking the task. However, when looking at our flow it would make more sense to assign the pull request to the person that actually invoked the pipeline in the first place. Is this something that can be done in DevOps?

Thanks!

**Comment by shayki5** [comment] 2020-07-22 14:09
Hi @wouterroos,
It's a good idea! I start to work on it :)

**Comment by wouterroos** [comment] 2020-07-22 16:31
@shayki5 great, looking forward to it! I've looked at the DevOps API spec and it should be possible. Other tasks usually allow you to supply the email address of the user so that would be great. Let me know if you need any assistance.

**Comment by shayki5** [comment] 2020-07-23 06:50
@wouterroos I tried to implement it with:
```
    "createdBy":  {
                      "id":  "some-user-id"
                  },
```

But the PR still created with the build user.
When I looked in a real call in the browser when I create manually a PR  see that the `createdBy` didn't pass in the JSON.
I made some research and I came to this issue:
https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/403

So, for now it looks like it's impossible to override the PR creator.

**Comment by wouterroos** [comment] 2020-07-23 07:12
@shayki5 that's a shame. I upvoted the issue you mentioned so that it might get some visibility. I guess we have to wait for a response from Microsoft...

**Comment by wouterroos** [comment] 2020-07-23 07:18
@shayki5 also see: https://developercommunity.visualstudio.com/content/problem/459964/changed-createdby-with-git-create-pull-request-api.html

**Comment by shayki5** [comment] 2020-07-23 07:42
@wouterroos the problem is Microsoft doesn't respond to the issues there :(
Maybe it worth open a new request in https://developercommunity.visualstudio.com

**Comment by shayki5** [comment] 2020-08-26 10:46
I closing the issue for now, because it looks like is impossible until MS will enable it.

**Closed by shayki5** 2020-08-26 10:46 UTC
Labels: enhancement
