### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mgSDBB** [shayki5/azure-devops-create-pr-task#43] opened 2020-05-26 17:57 UTC
![image](https://user-images.githubusercontent.com/32093007/82934047-2ea42000-9f8b-11ea-9cae-a86719b8d1e4.png)

26-05-26T17:53:09.4059963Z ##[error]{"$id":"1","innerException":null,"message":"Object reference not set to an instance of an object.","typeName":"System.NullReferenceException, mscorlib","typeKey":"NullReferenceException","errorCode":0,"eventId":0}

**Comment by shayki5** [comment] 2020-05-26 19:18
Hi @mgSDBB,
Can you run it again with the variable `system.debug` = `true` and share here the logs?

**Comment by mgSDBB** [comment] 2020-05-26 19:51
2020-05-26T19:47:38.9039548Z ##[debug]Evaluating condition for step: 'Create Pull Request'
2020-05-26T19:47:38.9040511Z ##[debug]Evaluating: succeeded()
2020-05-26T19:47:38.9040625Z ##[debug]Evaluating succeeded:
2020-05-26T19:47:38.9040816Z ##[debug]=> True
2020-05-26T19:47:38.9041012Z ##[debug]Result: True
2020-05-26T19:47:38.9041254Z ##[section]Starting: Create Pull Request
2020-05-26T19:47:38.9045783Z ==============================================================================
2020-05-26T19:47:38.9045850Z Task         : Create Pull Request
2020-05-26T19:47:38.9045885Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2020-05-26T19:47:38.9046465Z Version      : 1.2.132
2020-05-26T19:47:38.9046515Z Author       : Shayki Abramczyk
2020-05-26T19:47:38.9046552Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2020-05-26T19:47:38.9046602Z ==============================================================================
2020-05-26T19:47:39.8447302Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2020-05-26T19:47:39.9870590Z ##[debug]Entering RunTask.
2020-05-26T19:47:40.0193411Z ##[debug]INPUT_SOURCEBRANCH: 'refs/heads/develop'
2020-05-26T19:47:40.0217980Z ##[debug]INPUT_TARGETBRANCH: 'test-candidate'
2020-05-26T19:47:40.0263964Z ##[debug]INPUT_TITLE: 'Deploy Test'
2020-05-26T19:47:40.0286795Z ##[debug]INPUT_DESCRIPTION: 'Deploy Test'
2020-05-26T19:47:40.0310852Z ##[debug]INPUT_REVIEWERS: ‘-removed-‘
2020-05-26T19:47:40.0315089Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2020-05-26T19:47:40.0375375Z ##[debug]INPUT_ISDRAFT: 'false'
2020-05-26T19:47:40.0375981Z ##[debug] Converted to bool: False
2020-05-26T19:47:40.0387623Z ##[debug]INPUT_AUTOCOMPLETE: 'true'
2020-05-26T19:47:40.0403622Z ##[debug] Converted to bool: True
2020-05-26T19:47:40.0427166Z ##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
2020-05-26T19:47:40.0450455Z ##[debug]INPUT_DELETESOURCH: 'false'
2020-05-26T19:47:40.0466358Z ##[debug] Converted to bool: False
2020-05-26T19:47:40.0489600Z ##[debug]INPUT_COMMITMESSAGE (empty)
2020-05-26T19:47:40.0544083Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
2020-05-26T19:47:40.0559627Z ##[debug] Converted to bool: False
2020-05-26T19:47:40.0584951Z ##[debug]INPUT_LINKWORKITEMS: 'true'
2020-05-26T19:47:40.0600538Z ##[debug] Converted to bool: True
2020-05-26T19:47:40.0627976Z ##[debug]INPUT_PROJECTID (empty)
2020-05-26T19:47:40.0646188Z ##[debug]INPUT_GITREPOSITORYID (empty)
2020-05-26T19:47:40.0670301Z ##[debug]INPUT_GITHUBREPOSITORY: 'LSR'
2020-05-26T19:47:40.1573795Z The Source Branch is: refs/heads/develop
2020-05-26T19:47:40.1582058Z The Target Branch is: refs/heads/test-candidate
2020-05-26T19:47:40.1588209Z The Title is: Deploy Test
2020-05-26T19:47:40.1594479Z The Description is: Deploy Test
2020-05-26T19:47:40.1600532Z Is Reviewers are: -removed-
2020-05-26T19:47:40.1642417Z Is Draft Pull Request: False
2020-05-26T19:47:40.1886545Z ##[debug]GET https://devops.sdbb.ch/DefaultCollection/LSR/_apis/git/repositories/LSR/diffs/commits?baseVersion=develop&targetVersion=test-candidate&api-version=4.1&$top=2 with 0-byte payload
2020-05-26T19:47:40.2236523Z ##[debug]received 263-byte response of content type application/json; charset=utf-8; api-version=4.1
2020-05-26T19:47:40.2272883Z 1 new commits! perofrm a Pull Request...
2020-05-26T19:47:40.2346831Z ##[debug]GET https://devops.sdbb.ch/DefaultCollection/_apis/projects/LSR/teams?api-version=4.1 with 0-byte payload
2020-05-26T19:47:40.2491492Z ##[debug]received -1-byte response of content type application/json; charset=utf-8; api-version=4.1
2020-05-26T19:47:40.2572301Z ##[debug]-removed.
2020-05-26T19:47:40.2725693Z ##[debug]GET https://devops.sdbb.ch/DefaultCollection/_apis/projects/LSR/teams/67eb0c24-3546-4bbd-8796-d19da5b29143/members?api-version=4.1 with 0-byte payload
2020-05-26T19:47:40.2989767Z ##[debug]received -1-byte response of content type application/json; charset=utf-8; api-version=4.1
2020-05-26T19:47:40.3093830Z ##[debug]GET https://devops.sdbb.ch/DefaultCollection/_apis/projects/LSR/teams/a5abdb3c-d986-4e57-bc59-b4a3f55470ed/members?api-version=4.1 with 0-byte payload
2020-05-26T19:47:40.3274360Z ##[debug]received -1-byte response of content type application/json; charset=utf-8; api-version=4.1
2020-05-26T19:47:40.3318565Z The reviewers are: -removed-
2020-05-26T19:47:40.4607864Z ##[debug]{
2020-05-26T19:47:40.4608848Z ##[debug]    "compareVersion":  {
2020-05-26T19:47:40.4613782Z ##[debug]                           "versionOptions":  0,
2020-05-26T19:47:40.4635691Z ##[debug]                           "versionType":  0,
2020-05-26T19:47:40.4636210Z ##[debug]                           "version":  "develop"
2020-05-26T19:47:40.4644999Z ##[debug]                       },
2020-05-26T19:47:40.4653875Z ##[debug]    "itemVersion":  {
2020-05-26T19:47:40.4663029Z ##[debug]                        "versionOptions":  0,
2020-05-26T19:47:40.4671973Z ##[debug]                        "versionType":  0,
2020-05-26T19:47:40.4680934Z ##[debug]                        "version":  "test-candidate"
2020-05-26T19:47:40.4691203Z ##[debug]                    },
2020-05-26T19:47:40.4700194Z ##[debug]    "$top":  101,
2020-05-26T19:47:40.4708338Z ##[debug]    "includeWorkItems":  "true"
2020-05-26T19:47:40.4715244Z ##[debug]}
2020-05-26T19:47:40.4753111Z ##[debug]POST https://devops.sdbb.ch/DefaultCollection/LSR/_apis/git/repositories/LSR/commitsBatch?api-version=4.1 with -1-byte payload
2020-05-26T19:47:40.5070340Z ##[debug]received 676-byte response of content type application/json; charset=utf-8; api-version=4.1
2020-05-26T19:47:40.5072510Z ##[debug]@{count=1; value=System.Object[]}
2020-05-26T19:47:40.5166402Z {
2020-05-26T19:47:40.5166597Z     "sourceRefName":  "refs/heads/develop",
2020-05-26T19:47:40.5166681Z     "title":  "Deploy Test",
2020-05-26T19:47:40.5167402Z     "WorkItemRefs":  [
2020-05-26T19:47:40.5169524Z                          null
2020-05-26T19:47:40.5169642Z                      ],
2020-05-26T19:47:40.5170455Z     "description":  "Deploy Test",
2020-05-26T19:47:40.5171005Z     "reviewers":  [
2020-05-26T19:47:40.5171250Z
2020-05-26T19:47:40.5171988Z                   ],
2020-05-26T19:47:40.5172260Z     "isDraft":  "False",
2020-05-26T19:47:40.5172396Z     "targetRefName":  "refs/heads/test-candidate"
2020-05-26T19:47:40.5172556Z }
2020-05-26T19:47:40.5193741Z ##[debug]POST https://devops.sdbb.ch/DefaultCollection/LSR/_apis/git/repositories/LSR/pullrequests?api-version=5.0 with -1-byte payload
2020-05-26T19:47:40.5883306Z ##[debug]Leaving RunTask.
2020-05-26T19:47:40.5935861Z ##[debug]Caught exception from task script.
2020-05-26T19:47:40.5965081Z ##[debug]Error record:
2020-05-26T19:47:40.6716243Z ##[debug]CreateAzureDevOpsPullRequest : {"$id":"1","innerException":null,"message":"Object reference not set to an instance of an object.","typeName":"System.NullReferenceException, mscorlib","typeKey":"NullReferenceException","errorCode":0,"eventId":0}
2020-05-26T19:47:40.6725009Z ##[debug]At C:\agent\_work\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.132\createPullRequest.ps1:97 char:9
2020-05-26T19:47:40.6734838Z ##[debug]+         CreateAzureDevOpsPullRequest -teamProject $teamProject -repos ...
2020-05-26T19:47:40.6743665Z ##[debug]+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-05-26T19:47:40.6752776Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
2020-05-26T19:47:40.6761690Z ##[debug]    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,CreateAzureDevOpsPullRequest
2020-05-26T19:47:40.6770607Z ##[debug]
2020-05-26T19:47:40.6786474Z ##[debug]Script stack trace:
2020-05-26T19:47:40.6820538Z ##[debug]at CreateAzureDevOpsPullRequest, C:\agent\_work\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.132\createPullRequest.ps1: line 303
2020-05-26T19:47:40.6829509Z ##[debug]at CreatePullRequest, C:\agent\_work\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.132\createPullRequest.ps1: line 97
2020-05-26T19:47:40.6838535Z ##[debug]at RunTask, C:\agent\_work\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.132\createPullRequest.ps1: line 52
2020-05-26T19:47:40.6847414Z ##[debug]at <ScriptBlock>, C:\agent\_work\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.132\createPullRequest.ps1: line 571
2020-05-26T19:47:40.6856609Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-05-26T19:47:40.6865830Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-05-26T19:47:40.6875142Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-05-26T19:47:40.6883978Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-05-26T19:47:40.6900053Z ##[debug]Exception:
2020-05-26T19:47:40.6938680Z ##[debug]Microsoft.PowerShell.Commands.WriteErrorException: {"$id":"1","innerException":null,"message":"Object reference not set to an instance of an object.","typeName":"System.NullReferenceException, mscorlib","typeKey":"NullReferenceException","errorCode":0,"eventId":0}
2020-05-26T19:47:40.7223827Z ##[error]{"$id":"1","innerException":null,"message":"Object reference not set to an instance of an object.","typeName":"System.NullReferenceException, mscorlib","typeKey":"NullReferenceException","errorCode":0,"eventId":0}
2020-05-26T19:47:40.7232419Z ##[debug]Processed: ##vso[task.logissue type=error]{"$id":"1","innerException":null,"message":"Object reference not set to an instance of an object.","typeName":"System.NullReferenceException, mscorlib","typeKey":"NullReferenceException","errorCode":0,"eventId":0}
2020-05-26T19:47:40.7244756Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-05-26T19:47:40.7555492Z ##[section]Finishing: Create Pull Request

**Comment by shayki5** [comment] 2020-05-27 09:23
Can you try without reviewers?

**Comment by mgSDBB** [comment] 2020-05-27 11:41
Azure DevOps Server
Version 17.143.28912.1

I tried without reviewer, however the problem is still the same.

Pull requests seems to be created but not completed 
![image](https://user-images.githubusercontent.com/32093007/83014843-b8053200-a01f-11ea-85ed-e7e5c65802cd.png)

I have to reject it and abandon it.


2020-05-27T11:38:43.8403435Z ##[debug]Evaluating condition for step: 'Create Pull Request'
2020-05-27T11:38:43.8404804Z ##[debug]Evaluating: succeeded()
2020-05-27T11:38:43.8404954Z ##[debug]Evaluating succeeded:
2020-05-27T11:38:43.8405201Z ##[debug]=> True
2020-05-27T11:38:43.8406431Z ##[debug]Result: True
2020-05-27T11:38:43.8406709Z ##[section]Starting: Create Pull Request
2020-05-27T11:38:43.8412561Z ==============================================================================
2020-05-27T11:38:43.8412625Z Task         : Create Pull Request
2020-05-27T11:38:43.8412684Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2020-05-27T11:38:43.8468378Z Version      : 1.2.132
2020-05-27T11:38:43.8468558Z Author       : Shayki Abramczyk
2020-05-27T11:38:43.8468625Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2020-05-27T11:38:43.8468718Z ==============================================================================
2020-05-27T11:38:44.8425751Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2020-05-27T11:38:44.9972687Z ##[debug]Entering RunTask.
2020-05-27T11:38:45.0305563Z ##[debug]INPUT_SOURCEBRANCH: 'refs/heads/develop'
2020-05-27T11:38:45.0331931Z ##[debug]INPUT_TARGETBRANCH: 'test-candidate'
2020-05-27T11:38:45.0377345Z ##[debug]INPUT_TITLE: 'Deploy Test'
2020-05-27T11:38:45.0401084Z ##[debug]INPUT_DESCRIPTION: 'Deploy Test'
2020-05-27T11:38:45.0442028Z ##[debug]INPUT_REVIEWERS (empty)
2020-05-27T11:38:45.0462181Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2020-05-27T11:38:45.0511329Z ##[debug]INPUT_ISDRAFT: 'false'
2020-05-27T11:38:45.0535039Z ##[debug] Converted to bool: False
2020-05-27T11:38:45.0540268Z ##[debug]INPUT_AUTOCOMPLETE: 'true'
2020-05-27T11:38:45.0557900Z ##[debug] Converted to bool: True
2020-05-27T11:38:45.0582850Z ##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
2020-05-27T11:38:45.0606187Z ##[debug]INPUT_DELETESOURCH: 'false'
2020-05-27T11:38:45.0623633Z ##[debug] Converted to bool: False
2020-05-27T11:38:45.0647660Z ##[debug]INPUT_COMMITMESSAGE (empty)
2020-05-27T11:38:45.0673516Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
2020-05-27T11:38:45.0690792Z ##[debug] Converted to bool: False
2020-05-27T11:38:45.0715426Z ##[debug]INPUT_LINKWORKITEMS: 'true'
2020-05-27T11:38:45.0730690Z ##[debug] Converted to bool: True
2020-05-27T11:38:45.0755437Z ##[debug]INPUT_PROJECTID (empty)
2020-05-27T11:38:45.0779515Z ##[debug]INPUT_GITREPOSITORYID (empty)
2020-05-27T11:38:45.0804161Z ##[debug]INPUT_GITHUBREPOSITORY: 'LSR'
2020-05-27T11:38:45.1867733Z The Source Branch is: refs/heads/develop
2020-05-27T11:38:45.1872753Z The Target Branch is: refs/heads/test-candidate
2020-05-27T11:38:45.1877627Z The Title is: Deploy Test
2020-05-27T11:38:45.1882377Z The Description is: Deploy Test
2020-05-27T11:38:45.1887295Z Is Reviewers are: 
2020-05-27T11:38:45.1928654Z Is Draft Pull Request: False
2020-05-27T11:38:45.2183109Z ##[debug]GET https://devops.sdbb.ch/DefaultCollection/LSR/_apis/git/repositories/LSR/diffs/commits?baseVersion=develop&targetVersion=test-candidate&api-version=4.1&$top=2 with 0-byte payload
2020-05-27T11:38:45.2503963Z ##[debug]received 263-byte response of content type application/json; charset=utf-8; api-version=4.1
2020-05-27T11:38:45.2542138Z 1 new commits! perofrm a Pull Request...
2020-05-27T11:38:45.2722518Z ##[debug]{
2020-05-27T11:38:45.2733594Z ##[debug]    "compareVersion":  {
2020-05-27T11:38:45.2743382Z ##[debug]                           "versionOptions":  0,
2020-05-27T11:38:45.2753794Z ##[debug]                           "versionType":  0,
2020-05-27T11:38:45.2763614Z ##[debug]                           "version":  "develop"
2020-05-27T11:38:45.2773534Z ##[debug]                       },
2020-05-27T11:38:45.2783287Z ##[debug]    "itemVersion":  {
2020-05-27T11:38:45.3566437Z ##[debug]                        "versionOptions":  0,
2020-05-27T11:38:45.3567627Z ##[debug]                        "versionType":  0,
2020-05-27T11:38:45.3569505Z ##[debug]                        "version":  "test-candidate"
2020-05-27T11:38:45.3569773Z ##[debug]                    },
2020-05-27T11:38:45.3570009Z ##[debug]    "$top":  101,
2020-05-27T11:38:45.3570437Z ##[debug]    "includeWorkItems":  "true"
2020-05-27T11:38:45.3570662Z ##[debug]}
2020-05-27T11:38:45.3571025Z ##[debug]POST https://devops.sdbb.ch/DefaultCollection/LSR/_apis/git/repositories/LSR/commitsBatch?api-version=4.1 with -1-byte payload
2020-05-27T11:38:45.3571300Z ##[debug]received 663-byte response of content type application/json; charset=utf-8; api-version=4.1
2020-05-27T11:38:45.3571535Z ##[debug]@{count=1; value=System.Object[]}
2020-05-27T11:38:45.3744167Z {
2020-05-27T11:38:45.3750385Z     "sourceRefName":  "refs/heads/develop",
2020-05-27T11:38:45.3751150Z     "title":  "Deploy Test",
2020-05-27T11:38:45.3752048Z     "WorkItemRefs":  [
2020-05-27T11:38:45.3752515Z                          null
2020-05-27T11:38:45.3753127Z                      ],
2020-05-27T11:38:45.3753604Z     "description":  "Deploy Test",
2020-05-27T11:38:45.3754161Z     "reviewers":  "",
2020-05-27T11:38:45.3754677Z     "isDraft":  "False",
2020-05-27T11:38:45.3755453Z     "targetRefName":  "refs/heads/test-candidate"
2020-05-27T11:38:45.3755893Z }
2020-05-27T11:38:45.3768652Z ##[debug]POST https://devops.sdbb.ch/DefaultCollection/LSR/_apis/git/repositories/LSR/pullrequests?api-version=5.0 with -1-byte payload
2020-05-27T11:38:45.4460305Z ##[debug]Leaving RunTask.
2020-05-27T11:38:45.4501242Z ##[debug]Caught exception from task script.
2020-05-27T11:38:45.4537506Z ##[debug]Error record:
2020-05-27T11:38:45.5751650Z ##[debug]CreateAzureDevOpsPullRequest : {"$id":"1","innerException":null,"message":"Object reference not set to an instance of an object.","typeName":"System.NullReferenceException, mscorlib","typeKey":"NullReferenceException","errorCode":0,"eventId":0}
2020-05-27T11:38:45.5810023Z ##[debug]At C:\agent\_work\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.132\createPullRequest.ps1:97 char:9
2020-05-27T11:38:45.5810210Z ##[debug]+         CreateAzureDevOpsPullRequest -teamProject $teamProject -repos ...
2020-05-27T11:38:45.5810304Z ##[debug]+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-05-27T11:38:45.5810404Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
2020-05-27T11:38:45.5810503Z ##[debug]    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,CreateAzureDevOpsPullRequest
2020-05-27T11:38:45.5810572Z ##[debug] 
2020-05-27T11:38:45.5815036Z ##[debug]Script stack trace:
2020-05-27T11:38:45.5843966Z ##[debug]at CreateAzureDevOpsPullRequest, C:\agent\_work\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.132\createPullRequest.ps1: line 303
2020-05-27T11:38:45.5853139Z ##[debug]at CreatePullRequest, C:\agent\_work\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.132\createPullRequest.ps1: line 97
2020-05-27T11:38:45.5861561Z ##[debug]at RunTask, C:\agent\_work\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.132\createPullRequest.ps1: line 52
2020-05-27T11:38:45.5870231Z ##[debug]at <ScriptBlock>, C:\agent\_work\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.132\createPullRequest.ps1: line 571
2020-05-27T11:38:45.5878908Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-05-27T11:38:45.5887929Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-05-27T11:38:45.5896415Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-05-27T11:38:45.5905063Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-05-27T11:38:45.5919240Z ##[debug]Exception:
2020-05-27T11:38:45.5954995Z ##[debug]Microsoft.PowerShell.Commands.WriteErrorException: {"$id":"1","innerException":null,"message":"Object reference not set to an instance of an object.","typeName":"System.NullReferenceException, mscorlib","typeKey":"NullReferenceException","errorCode":0,"eventId":0}
2020-05-27T11:38:45.6227639Z ##[error]{"$id":"1","innerException":null,"message":"Object reference not set to an instance of an object.","typeName":"System.NullReferenceException, mscorlib","typeKey":"NullReferenceException","errorCode":0,"eventId":0}
2020-05-27T11:38:45.6236739Z ##[debug]Processed: ##vso[task.logissue type=error]{"$id":"1","innerException":null,"message":"Object reference not set to an instance of an object.","typeName":"System.NullReferenceException, mscorlib","typeKey":"NullReferenceException","errorCode":0,"eventId":0}
2020-05-27T11:38:45.6249671Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-05-27T11:38:45.6610595Z ##[section]Finishing: Create Pull Request

**Comment by shayki5** [comment] 2020-05-27 11:44
Oh, do you try yo auto-complete?
Can you share your task configuration?

**Comment by mgSDBB** [comment] 2020-05-27 12:03
Hi,
Yes I tried Auto-complete

[cid:image001.png@01D6342F.879C8F20]


.

**Comment by mgSDBB** [comment] 2020-05-27 12:05
![image](https://user-images.githubusercontent.com/32093007/83016999-28618280-a023-11ea-8f10-59fb75f142c5.png)

**Comment by mgSDBB** [comment] 2020-05-27 12:07
May it be around the work items because 
"includeWorkItems":  "true"
and
    $jsonBody = ConvertTo-Json $body
    Write-Host $jsonBody
the WorkItemsList is null?
 {
     "sourceRefName":  "refs/heads/develop",
     "title":  "Deploy Test",
     "WorkItemRefs":  [
                          null
                      ],
"description":  "Deploy Test",
     "reviewers":  "",
     "isDraft":  "False",
     "targetRefName":  "refs/heads/test-candidate"
 }

**Comment by shayki5** [comment] 2020-05-27 12:15
Try without the work items and if it not work try without the auto complete.
Thank you!

**Comment by mgSDBB** [comment] 2020-05-27 12:28
Ok it is working without the work items. The collection shouldn't be null.

**Comment by shayki5** [comment] 2020-05-27 13:35
It's wired, in my case is working without work items even I check the  "link work items", but it's in Azure DevOps and not Azure DevOps Server.

**Comment by shayki5** [comment] 2020-06-07 14:14
Can't reproduce the issue, closing.

**Closed by shayki5** 2020-06-07 14:14 UTC
